version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.node
    networks: 
      - node-nginx
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    networks: 
      - node-nginx
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    # volumes:
    #   - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-nginx

networks:
  node-nginx:
    driver: bridge
