version: '3'

services:
  nodeserver:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "5000:5000"
    networks: 
      - node-nginx
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    networks: 
      - node-nginx

# db:
#   image: mysql:5.7
#   command: --innodb-use-native-aio=0
#   container_name: db
#   restart: always
#   tty: true
#   volumes:
#     - ./mysql:/var/lib/mysql
#   environment:
#     - MYSQL_DATABASE=nodedb
#     - MYSQL_ROOT_PASSWORD=root
#   networks: 
#     - node-network

networks:
  node-nginx:
    driver: bridge
